version: "3.9"
services:
  book:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    volumes:
      -  .:/app
      - node_modules:/app/node_modules
    command: npx honkit serve --reload
volumes:
  node_modules:
    driver: local
