version: "3.9"
services:
  book:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    volumes:
      -  .:/app
      - modules:/app/node_modules
    command: npm run serve
    working_dir: /app
volumes:
  modules:
    driver: local
